apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-micro
  namespace: ameen2607-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-micro
  template:
    metadata:
      labels:
        app: spring-micro
    spec:
      containers:
      - name: spring-micro
        #image: 593793064016.dkr.ecr.eu-north-1.amazonaws.com/myecr-ameen:${{ github.sha }}
        image: __IMAGE__
        ports:
        - containerPort: 3001