apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: ameen2607-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-frontend
         #image: 593793064016.dkr.ecr.eu-north-1.amazonaws.com/myecr-ameen:${{ github.sha }}
        image: __IMAGE__
        ports:
        - containerPort: 3005
      