apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: ameen2607-dev
spec:
  selector:
    app: react-frontend
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
  type: ClusterIP