name: OpenShift Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-north-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: docker build -t ${{ steps.login-ecr.outputs.registry }}/myecr-ameen:${{ github.sha }} .

      - name: Push Docker image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/myecr-ameen:${{ github.sha }}

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ameen2607-dev

      - name: Apply deployment YAML
        run: oc apply -f k8s/deployment.yaml

      - name: Apply service YAML
        run: oc apply -f k8s/service.yaml

      - name: Apply route YAML
        run: oc apply -f k8s/route.yaml