name: OpenShift Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'react-frontend-app2/**'
      - 'k8s/react-frontend-app2/**'
    
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OpenShift CLI (oc)
        run: |
          curl -LO "https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz"
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin/oc
          oc version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: docker build -t ${{ steps.login-ecr.outputs.registry }}/myecr-ameen:$IMAGE_TAG ./react-frontend-app2

      - name: Push Docker image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/myecr-ameen:$IMAGE_TAG

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ameen2607-dev

      - name: Apply deployment YAML
        run: |
          IMAGE="${{ steps.login-ecr.outputs.registry }}/myecr-ameen:$IMAGE_TAG"
          sed "s|__IMAGE__|$IMAGE|g" k8s/react-frontend-app2-new/deployment.yaml > k8s/react-frontend-app2-new/deployment-patched.yaml
          oc apply -f k8s/react-frontend-app2-new/deployment-patched.yaml
        
      - name: Apply service YAML
        run: oc apply -f k8s/react-frontend-app2-new/service.yaml

      - name: Apply route YAML
        run: oc apply -f k8s/react-frontend-app2-new/route.yaml